### ISSUE TITLE
Still having issues.

### ISSUE THREAD

**Issue by Zand3rsCode** [khemh/The-Curator#1]
Tried using your new commit, its still not working now the file is not written to at all.
I am not sure how much you really care but i thought i would be kind enough  and tell you!

**Comment by khemh** [comment]
I appreciate the feedback, if you were getting a permission denied error the code should work now. If not please let me know if theres any error that pops up as the code is running fine on my end.

**Comment by Zand3rsCode** [comment]
Working great! Good job! :)
